import { cliExportOutputSchema } from '@impactgraph/contracts';
import { buildExportOutput } from '@impactgraph/workspace-engine';

import { writeJson, writeLines } from '../output.js';

import type { CommandContext } from '../context.js';
import type {
  ExpectationExport,
  ImpactSummaryExport,
  ImplementationContext,
} from '@impactgraph/application';

// §38.1 impact-report renderers (18 sections, exact order). Markdown targets both humans and
// coding agents; JSON is the schema-stable §22 context.

export interface ExportRenderInput {
  readonly context: ImplementationContext;
  readonly possibleImpacts: readonly ImpactSummaryExport[];
  readonly affectedContexts: readonly string[];
  readonly evidenceFileById: ReadonlyMap<string, string>;
}

const list = (items: readonly string[]): string[] => (items.length === 0 ? ['_none_'] : [...items]);

const impactLines = (impacts: readonly ImpactSummaryExport[]): string[] =>
  list(
    impacts.map(
      (impact) =>
        `- **${impact.name}**${impact.path === undefined ? '' : ` (\`${impact.path}\`)`} — ${impact.impactType}, ${impact.directness}, confidence ${impact.confidence.toFixed(2)}: ${impact.explanation}`,
    ),
  );

const expectationLines = (items: readonly ExpectationExport[]): string[] =>
  list(
    items.map(
      (item) =>
        `- **${item.name}**${item.path === undefined ? '' : ` (\`${item.path}\`)`} — ${item.reason}`,
    ),
  );

const byImpactType = (input: ExportRenderInput, types: readonly string[]): ImpactSummaryExport[] =>
  [...input.context.requiredImpacts, ...input.context.likelyImpacts].filter((impact) =>
    types.includes(impact.impactType),
  );

const specificationSections = (input: ExportRenderInput): string[] => {
  const spec = input.context.specification;
  return [
    '# Implementation Context',
    '',
    '## 1. Specification Summary',
    '',
    `**${spec.title}** (${spec.id} v${String(spec.version)}, ${spec.sourceType}) — ${String(spec.requirements.length)} requirement(s).`,
    '',
    '## 2. Extracted Requirements',
    '',
    ...list(spec.requirements.map((req) => `- **${req.id}** (${req.type}): ${req.statement}`)),
    '',
    '## 3. Open Questions',
    '',
    ...list(spec.openQuestions.map((q) => `- [${q.severity}] ${q.question} (${q.status})`)),
    '',
    '## 4. Affected Contexts',
    '',
    ...list(input.affectedContexts.map((name) => `- ${name}`)),
  ];
};

const impactSections = (input: ExportRenderInput): string[] => [
  '',
  '## 5. Required Impacts',
  '',
  ...impactLines(input.context.requiredImpacts),
  '',
  '## 6. Likely Impacts',
  '',
  ...impactLines(input.context.likelyImpacts),
  '',
  '## 7. Possible Impacts',
  '',
  ...impactLines(input.possibleImpacts),
  '',
  '## 8. Data and Migration Impact',
  '',
  ...expectationLines(input.context.expectedMigrations),
  '',
  '## 9. API Impact',
  '',
  ...impactLines(byImpactType(input, ['api-contract'])),
  '',
  '## 10. Event and Messaging Impact',
  '',
  ...impactLines(byImpactType(input, ['event-contract'])),
  '',
  '## 11. Infrastructure Impact',
  '',
  ...expectationLines(input.context.expectedInfrastructureChanges),
  '',
  '## 12. Security Impact',
  '',
  ...impactLines(byImpactType(input, ['security'])),
  '',
  '## 13. Test Expectations',
  '',
  ...expectationLines(input.context.expectedTests),
];

const closingSections = (input: ExportRenderInput): string[] => {
  const { context } = input;
  const snapshot = context.repositorySnapshot;
  return [
    '',
    '## 14. Architectural Alternatives',
    '',
    ...list(
      context.approvedAnalysis.architecturalOptions.map(
        (option) => `- **${option.title}** — ${option.description}`,
      ),
    ),
    '',
    '## 15. Risks',
    '',
    ...list(context.openWarnings.map((warning) => `- [${warning.code}] ${warning.message}`)),
    '',
    '## 16. User Decisions',
    '',
    ...list(
      context.approvedAnalysis.userDecisions.map(
        (decision) =>
          `- ${decision.decision}: ${decision.nodeId} (requirement ${decision.requirementId})${decision.reason === undefined ? '' : ` — ${decision.reason}`}`,
      ),
    ),
    '',
    '## 17. Evidence',
    '',
    ...list([...input.evidenceFileById.entries()].map(([id, file]) => `- \`${id}\` → ${file}`)),
    '',
    '## 18. Repository Snapshot',
    '',
    `Snapshot \`${snapshot.id}\`${snapshot.branch === undefined ? '' : ` on branch \`${snapshot.branch}\``} at commit \`${snapshot.commitSha}\` (dirty: ${String(snapshot.dirtyWorkingTree)}, indexed ${snapshot.createdAt}).`,
    '',
    '> Generated by ImpactGraph from the approved analysis. Coverage of expectations is an estimate — the review step verifies the implementation (§25).',
  ];
};

const textSummary = (input: ExportRenderInput): string[] => [
  `Implementation context for analysis ${input.context.approvedAnalysis.id} (snapshot ${input.context.repositorySnapshot.id})`,
  `  required: ${String(input.context.requiredImpacts.length)}  likely: ${String(input.context.likelyImpacts.length)}  rejected: ${String(input.context.rejectedImpacts.length)}`,
  `  expected tests: ${String(input.context.expectedTests.length)}  migrations: ${String(input.context.expectedMigrations.length)}  infra: ${String(input.context.expectedInfrastructureChanges.length)}`,
  `  constraints: ${String(input.context.architectureConstraints.length)}  review criteria: ${String(input.context.reviewCriteria.length)}`,
  'Use --format markdown for the full §38.1 report or --format json for the §22 context.',
];

export const renderExport = (context: CommandContext, input: ExportRenderInput): void => {
  if (context.format === 'json') {
    writeJson(context, cliExportOutputSchema, buildExportOutput(input.context));
    return;
  }
  writeLines(
    context,
    context.format === 'markdown'
      ? [...specificationSections(input), ...impactSections(input), ...closingSections(input)]
      : textSummary(input),
  );
};
